--Cadastrar Dentistas
CREATE TRIGGER CADASTRARDENTISTAS
ON DENTISTAS
AFTER INSERT 
AS
BEGIN INSERT INTO LOGS(DESCRICAO, DENTISTAID, PACIENTEID)
	SELECT CONCAT('Cadastro de Dentista: ', i.Nome), 
		i.DentistaID, 
		0
		FROM INSERTED I
END;

--Atualizar Dentistas
CREATE TRIGGER ATUALIZARDENTISTAS
ON DENTISTAS
AFTER UPDATE
AS
BEGIN INSERT INTO LOGS(DESCRICAO, DENTISTAID, PACIENTEID)
	SELECT CONCAT('Atualização de Dentista: ', i.DentistaID),
		i.DentistaID,
		0
		FROM INSERTED I
END;

--Excluir Dentistas
CREATE TRIGGER EXCLUIRDENTISTAS
ON DENTISTAS
AFTER DELETE
AS 
BEGIN INSERT INTO LOGS(DESCRICAO, DENTISTAID, PACIENTEID)
	SELECT CONCAT('Exclusão de Dentista: ', d.DentistaID),
	d.DentistaID,
	0
	FROM DELETED D
END;