USE odontoDB;

--Cadastrar Documentos
CREATE TRIGGER CADASTRARDOCUMENTO
ON DOCUMENTOS
AFTER INSERT
AS
BEGIN INSERT INTO LOGS(DESCRICAO, DENTISTAID, PACIENTEID)
    SELECT CONCAT('Cadastrando Documento: ', i.DocumentoID),
    i.DentistaID,
    i.PACIENTEID
    FROM INSERTED I
END;

--Atualizar Documentos
CREATE TRIGGER ATUALIZARDOCUMENTO
ON DOCUMENTOS
AFTER UPDATE
AS
BEGIN INSERT INTO LOGS(DESCRICAO, DENTISTAID, PACIENTEID)
    SELECT CONCAT('Cadastrando Documento: ', i.DocumentoID),
    i.DentistaID,
    i.PACIENTEID
    FROM INSERTED I
END;

--Excluir Documentos
CREATE TRIGGER EXCLUIRDOCUMENTO
ON DOCUMENTOS
AFTER DELETE
AS
BEGIN INSERT INTO LOGS(DESCRICAO, DENTISTAID, PACIENTEID)
    SELECT CONCAT('Cadastrando Documento: ', i.DocumentoID),
    i.DentistaID,
    i.PACIENTEID
    FROM INSERTED I
END;


