USE odontoDB;

--Cadastrar Pacientes
CREATE TRIGGER CADASTRARPACIENTE
ON PACIENTES
AFTER INSERT
AS
BEGIN INSERT INTO LOGS(DESCRICAO, DENTISTAID, PACIENTEID)
    SELECT CONCAT('Cadastrando Paciente: ', i.PACIENTEID),
    0,
    i.PACIENTEID
    FROM INSERTED I
END;

--Atualizar Pacientes
CREATE TRIGGER ATUALIZARPACIENTE
ON PACIENTES
AFTER UPDATE
AS
BEGIN INSERT INTO LOGS(DESCRICAO, DENTISTAID, PACIENTEID)
    SELECT CONCAT('Atualizando Paciente:', i.PACIENTEID),
    0,
    i.PACIENTEID
    FROM INSERTED I
END;

--Excluir Pacientes
CREATE TRIGGER EXCLUIRPACIENTES
ON PACIENTES
AFTER DELETE
AS
BEGIN INSERT INTO LOGS(DESCRICAO, DENTISTAID, PACIENTEID)
    SELECT CONCAT('Excluindo Paciente: ', i.PACIENTEID),
    0,
    i.PACIENTEID
    FROM INSERTED I
END;