CREATE TABLE Logs
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	DESCRICAO NVARCHAR(255),
	DENTISTAID INT,
	PACIENTEID INT
)
--Criacao de Gatilhos de Consultas

--Gatilho de Marcacao de Consulta
CREATE TRIGGER MARCARCONSULTA
ON CONSULTAS
AFTER INSERT
AS
BEGIN
	INSERT INTO LOGS(DESCRICAO, DENTISTAID, PACIENTEID)
	SELECT CONCAT('Marca��o de consulta: ', i.DESCRICAO),
		I.DENTISTAID,
		I.PACIENTEID
		FROM INSERTED I
END;

--Gatilho de Atualizacao de Consulta
CREATE TRIGGER ATUALIZARCONSULTA
ON CONSULTAS
AFTER UPDATE
AS
BEGIN
	INSERT INTO LOGS(DESCRICAO, DENTISTAID, PACIENTEID)
	SELECT CONCAT('Atualiza��o de Consulta id: ', d.ConsultaID),
		I.DENTISTAID,
		I.PACIENTEID
		FROM INSERTED I
		INNER JOIN DELETED D ON I.ConsultaId = D.ConsultaId
END;

--Gatilho de Exclusao de Consulta
CREATE TRIGGER EXCLUIRCONSULTA
ON CONSULTAS
AFTER DELETE
AS
BEGIN
	INSERT INTO LOGS(DESCRICAO, DENTISTAID, PACIENTEID)
	SELECT CONCAT('Exclus�o de Consulta id: ', d.ConsultaID),
		d.DentistaID,
		d.PacienteID
		FROM DELETED D
END;

SELECT * FROM LOGS